# Generated by Django 2.2.7 on 2020-01-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, unique=True)),
                ('descrioption', models.TextField(blank=True)),
                ('harga', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('publish', models.DateField()),
                ('is_publish', models.BooleanField(default=False)),
                ('cover', models.ImageField(upload_to='covers/')),
            ],
        ),
    ]
