# Generated by Django 2.2.7 on 2020-01-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.DateField(blank=True),
        ),
    ]
