# Generated by Django 2.2.7 on 2020-01-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200125_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
