# Generated by Django 2.2.7 on 2020-01-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200125_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_10', models.CharField(blank=True, max_length=30)),
                ('isbn_30', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.BookNumber'),
        ),
    ]
